name: pocketsync_flutter
description: "Pocketsync is a Flutter plugin that provides a simple way to sync your data between devices."
version: 0.4.2
homepage: https://pocketsync.dev
repository: https://github.com/pocketsync/pocketsync_flutter
topics: 
  - local-first
  - offline-first
  - sync

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  crypto: ^3.0.6
  device_info_plus: ^11.4.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  
  meta: ^1.16.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  sqlite3_flutter_libs: ^0.5.32
  socket_io_client: ^3.1.2
  uuid: ^4.5.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  fake_async: ^1.3.2
